### ISSUE TITLE
Expected output files

### ISSUE THREAD

**Issue by mkadlof** [mkadlof/pzh_pipeline_viral#16]
Expected output files for illumina: sars, infl, rsv
  
  output_MN908947_3.fasta
  output_hRSV_A_England_397_2017.fasta
  output_hRSV_B_England_RE20000104_2020.fasta
  output_chr1_PB2.fasta
  output_chr2_PB1.fasta
  output_chr3_PA.fasta
  output_chr4_HA.fasta
  output_chr5_NP.fasta
  output_chr6_NA.fasta
  output_chr7_MP.fasta
  output_chr8_NS.fasta
  output_M2.fasta

**Comment by michallaz** [comment]
Implemented in 89b799f
